# This workflow will install Python dependencies, run tests and lint with a
# single version of Python For more information see:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install uv based on version file
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
    - name: Install dependencies
      run: |
        uv venv
        uv pip install -r requirements.txt -r requirements-dev.txt
    - name: Run linters
      run: make lint
    - name: Run test suite
      run: make tests
